package org.telegram.graphic_contest.data.model;

import android.graphics.Color;

import java.util.ArrayList;
import java.util.List;


public class Axis {

    private static final int DEFAULT_TEXT_SIZE_SP = 12;
    private static final int DEFAULT_MAX_AXIS_LABEL_CHARS = 3;

    private int maxLabelChars = DEFAULT_MAX_AXIS_LABEL_CHARS;

    private List<AxisValue> values = new ArrayList<AxisValue>();

    private String name;

    private boolean isAutoGenerated = true;

    private boolean hasLines;


    private int textColor = Color.LTGRAY;

    private int lineColor = Color.parseColor("#DDDDDD");

    public Axis() {
    }

    public List<AxisValue> getValues() {
        return values;
    }

    public void setValues(final List<AxisValue> values) {
        if (null == values) {
            this.values = new ArrayList<>();
        } else {
            this.values = values;
        }

        this.isAutoGenerated = false;
    }

    public String getName() {
        return name;
    }

    public Axis setName(String name) {
        this.name = name;
        return this;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public boolean hasLines() {
        return hasLines;
    }

    public Axis setHasLines(boolean hasLines) {
        this.hasLines = hasLines;
        return this;
    }

    public int getTextColor() {
        return textColor;
    }

    public int getLineColor() {
        return lineColor;
    }

    public int getTextSize() {
        final int textSize = DEFAULT_TEXT_SIZE_SP;
        return textSize;
    }

    public int getMaxLabelChars() {
        return maxLabelChars;
    }


    public void setMaxLabelChars(int maxLabelChars) {
        if (maxLabelChars < 0) {
            maxLabelChars = 0;
        } else if (maxLabelChars > 32) {
            maxLabelChars = 32;
        }
        this.maxLabelChars = maxLabelChars;
    }
}
